main.cjs
sistemazione login + fix database access
Ora si può accedere al sistema con le seguenti credenziali:
username:admin, password:admin
username:cliente password:admin
username:adminz password:pizzamargherita
=> fix problemi

main.cjs
Andranno inseriti i tokens , nello sprint 1 o 2 , stasera ne discutiamo
=> Aggiunta accesso senza registrazione e pulsante per registrarsi

main.cjs, prodotto.cjs, public/mercato.html, public/templateprodotto.html
c'è qualche conflitto devo ancora vedere api per trovare il prodotto salvato
=> Schema per prodotto, visualizzazione2

classes/Venditore.cjs, classes/prodotto.cjs, main.cjs, models/productModel.cjs, public/templateprodotto.html, public/venditore.html, testapi.cjs
ho cambiato delle cose, purtroppo ho ritoccato delle cose anche del Database per provarlo, ho ridotto le categorie perchè volevo capire meglio come funzionava il salvataggio ma devo aver sbagliato qualcosa. In ogni caso accetta pure e domani sistemo bene DB e cerco di capire il salvataggio perchè per adesso non salva tutte le categorie e non capisco come mai.
=> Branch vendite

classes/Cliente.cjs, classes/Imprenditore.cjs, classes/Venditore.cjs, main.cjs, models/clientModel.cjs, models/productModel.cjs, models/promoterModel.cjs, models/promotionModel.cjs, models/vendorModel.cjs, public/venditore.html
Sistemato DB schemas e classes
-> tutti gli users hanno uno schema di riferimento funzionante e comincia con DB
-> DBPromoter è diventato DBEntrepeneur siccome è legata a imprenditore
-> il salvataggio dei Prodotti invece avviene tramite schema Productv2   ( possiamo rinominarlo e decidere insieme una nominazione degli schemi di base per tutto)
**Nota bene:**
Non ci sono foto per ora
Non ci sono colori per ora (aggiungibile tutto in un secondo momento se necessario, se mai per prodotto magari torna utile un colore per qualcosa di HTML)
Gli enum vengono trattati come stringhe
Per inserire e fare esperimenti potete usare la funzione del main insert() io faccio di solito prima con var p= costruttore di quello che vuoi e poi nomeschema.create(p), c'è anche un esempio commentato
=> Fix Database Schemas

main.cjs, public/carrello.html, public/mercato.html, public/prodotto.html, public/templateprodotto.html, services/ProdottoService.cjs, services/clienteService.cjs
Sistemato gli script HTML di prodotti e carrello (per ora mostra un solo prodotto). API in main per gli script e service functions.
=> Dynamic rendering di prodotti e carrello

main.cjs
by Rayan e Alessandro, appena fatta, ora funziona
=> fix issue carrello

main.cjs, public/dettaglivenditore.html, public/venditore.html, services/VenditoreService.cjs
test su Api venditori, 2 nuove pagine semplici
=> Pagina Venditori (tutti), Pagina venditore (Specifico)

classes/Carrello.cjs, main.cjs, models/clientModel.cjs, public/carrello.html, services/clienteService.cjs
=> Aggiunto quantita al carrello e gestito calcolo totale nel carrello

main.cjs, public/interfacciavenditore.html, public/mercato.html, public/nuovoprodotto.html, public/tuttiprodottiprivato.html, public/venditori.html, services/ProdottoService.cjs
-> tasto 2 pagina dedicata al futuro account venditore esclusivamente
Pubblicazione prodotti
Rimozione dei propri prodotti dalla bancarella con pagina privata simile a quella del mercato
Modifica quantità di prodotti (per ora solo grafica)
Per sprint1 mi resta:
Modifica quantità di prodotti dalla bancarella effettiva
Piccole migliorie alle pagine
C'è ancora da vedere la gestione dei tags e chiaramente il fatto che per ora così come il carrello, anche la pagina dei venditori è statica (per ora riguarda solo Caio Borghese), in ogni caso lo faremo all'inizio di S2 e non dovrebbe richiedere più di tanto.
=> Gestione pagina e user stories venditore

classes/Enums.cjs, main.cjs, models/clientModel.cjs, models/tagsModel.cjs, public/interfacciavenditore.html, public/nuovoprodotto.html, public/tuttiprodottiprivato.html, public/updateprodotto.html, services/ProdottoService.cjs, services/tagService.cjs
Aggiunti i tags definiti nella pubblicazione del prodotto  (come da UML). Sono salvati anche nel DB sotto DBTags e sono composti da id e array di stringhe.
Adesso testa al D3.
_Can't automatically merge. I conflitti potrebbero essere causati semplicemente da un nome di api poi cambiato._
=> Gestione definita dei tags prodotto e correzione di problemi minori

authcheck.cjs, classes/account.cjs, main.cjs, public/default.html, public/dettagliaccount.html, public/home.html, public/login.html, public/loginbusiness.html
Nuova gestione accesso 'Guest' momentaneamente dedicata ad accesso in ogni pagina.
Manderò in privato password e mail degli account per provare invece il funzionamento dei tokens.
Aggiunta pagina dettagli account che lavora in maniera dinamica (in base all'account utilizzato). La pagina e provvisoria
**Prossimi step personali:**
finire pagina dettagli account
aggiungere cambio di alcuni dettagli dell'account
sistemazione interfacce in base al ruolo
=> sistemazione account e gestione login

API/account.cjs, main.cjs, public/default.html, public/dettagliaccount.html, public/homev2(client).html, public/interfacciavenditore.html, public/login.html, public/registrazione.html, services/clienteService.cjs
-> Ora è possibile registrarsi
-> Correzione errori su tasti torna indietro
-> Nuova Home con upgrade (tasto) e Ordini (tasto)
**A seguire farò:**
Mappa e revisione interfacce
Ordini venditore con relative API
=> Feature registrazione + piccole modifiche ad interfacce (home, dettagliAccount, interfacciavenditore)

API/mail.cjs, main.cjs, package-lock.json, package.json, public/dettagliaccount.html, public/mercato.html, public/ordine.html, public/registrazione.html, public/tuttiprodotti.html
Implementato il sistema di e-mail di conferma, per ora statico (manda le mail solo a me). E' gratis per 60 gg.
**Nota**
@Tek2003 @LeonardoChiste dovete installare npm install --save @sendgrid/mail + configurare su .env personale una nuov stringa ossia SENDGRID_API_KEY='' con la stringa che vi mando in privato.
=> Aggiunta email di conferma dopo registrazione, modifiche grafiche

API/authcheck.cjs, API/mail.cjs, main.cjs, public/addPromo.html, public/businessarea.html, public/dettagliaccount.html, public/homev2(business).html, public/login.html, public/loginbusiness.html, public/nuovoprodotto.html, public/ordine.html, public/tuttiprodottiprivato.html
->interfacce sistemate come da schema condiviso
->fix bug token Imprenditore
->pagina venditore è ora dinamica in base al login (quello di Default è Piscitelli Antonello)
=> Pagina venditori dinamica, nuova BusinessArea e Home 

API/order.cjs, models/orderModel.cjs, models/promoterModel.cjs, public/ordine.html, public/ordinicliente.html
Pagina degli ordini dei clienti (Accesso consentito anche a Promotori e Venditori)
@LeonardoChiste , ho cambiato le API ordine e lo schema Ordine perché non funzionava con venditori e promotori. La pagina che avevi fatto per la visualizzazione delle consegne dell'admin va aggiustata. O lo faccio io domani o lo puoi fare tu guardando cosa ho cambiato in order.cjs e orderModel.cjs
=> Visualizzazione ordini

API/mail.cjs, public/homev2(business).html, public/homev2(client).html
prossimi passi miei:
pagina ordine venditori
aggiunta foto prodotti
=> Correzione mail e grafiche home

API/mail.cjs, API/order.cjs, main.cjs, public/ordinicliente.html, public/ordinivenditore.html, public/registrazione.html
=> Pagina ordinivenditore con opzione rifiuto (ed email), opzione set 'ritirato' cliente

API/order.cjs, main.cjs, public/ordinivenditore.html
=> nuovo filtro ordini, correzioni

public/carrello.html
Blocca accesso a ordine.html se carrello è vuoto
=> Carrello vuoto

package-lock.json, package.json, testing/carrelli.test.js
test cases per carrello usando jest e supertest
=> testing carrello
